# Generated by Django 3.1.3 on 2020-11-25 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(db_column='book_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('price', models.PositiveIntegerField(db_column='price')),
                ('rent_price', models.PositiveIntegerField(db_column='rent_price', null=True)),
                ('created_at', models.DateField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.AutoField(db_column='uid', primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(db_column='is_completed', default=False)),
                ('title', models.CharField(db_column='title', max_length=20)),
            ],
            options={
                'db_table': 'todos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=20, unique=True)),
                ('password', models.CharField(db_column='password', max_length=20)),
                ('email', models.CharField(db_column='email', default='123@gmail.com', max_length=20)),
                ('phone', models.CharField(db_column='phone', default='0912345678', max_length=20)),
                ('created_at', models.DateField(db_column='created_at', default=django.utils.timezone.now)),
                ('updated_at', models.DateField(db_column='updated_at', default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
