# Generated by Django 3.0.5 on 2020-05-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20200512_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(db_column='email', default='123@gmail.com', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(db_column='phone', default='0912345678', max_length=20),
        ),
    ]
